# Generated by Django 5.1.1 on 2025-04-07 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('likes', models.IntegerField(default=0)),
                ('headcount', models.IntegerField(default=0)),
                ('malecount', models.IntegerField(default=0)),
                ('femalecount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='account.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
